import React from 'react';
import Link from 'next/link';

export default function TermsOfService() {
  return (
    <main className="min-h-screen py-12 px-6">
      <div className="max-w-4xl mx-auto prose prose-neutral dark:prose-invert">
        <h1>Terms of Service</h1>
        <p className="text-muted-foreground">Last Updated: February 2026</p>

        <section className="mt-8">
          <h2>1. Agreement to Terms</h2>
          <p>
            By accessing or using the Lighted service ("Service"), you agree to be bound by 
            these Terms of Service ("Terms"). If you do not agree to these Terms, please do 
            not use our Service.
          </p>
          <p>
            These Terms constitute a legally binding agreement between you and Lighted, 
            governed by the laws of the Republic of South Africa, including the Consumer 
            Protection Act 68 of 2008 (CPA) and the Electronic Communications and 
            Transactions Act 25 of 2002 (ECTA).
          </p>
        </section>

        <section className="mt-8">
          <h2>2. Description of Service</h2>
          <p>
            Lighted provides a voice-to-exegesis service for pastors and religious leaders. 
            Users can:
          </p>
          <ul>
            <li>Send voice notes via Telegram containing sermon topics or scripture passages</li>
            <li>Receive AI-generated exegesis briefs based on their voice input</li>
            <li>Access and manage their exegesis briefs through our web application</li>
          </ul>
        </section>

        <section className="mt-8">
          <h2>3. User Accounts</h2>
          
          <h3>3.1 Account Creation</h3>
          <p>
            To use certain features of the Service, you must create an account. You may sign 
            up using Google authentication or by providing your email address.
          </p>

          <h3>3.2 Account Responsibilities</h3>
          <p>You are responsible for:</p>
          <ul>
            <li>Maintaining the confidentiality of your account credentials</li>
            <li>All activities that occur under your account</li>
            <li>Notifying us immediately of any unauthorized use</li>
          </ul>

          <h3>3.3 Account Requirements</h3>
          <p>
            You must be at least 18 years old to create an account and use our Service. 
            By creating an account, you represent that you meet this requirement.
          </p>
        </section>

        <section className="mt-8">
          <h2>4. Acceptable Use</h2>
          <p>You agree not to use the Service to:</p>
          <ul>
            <li>Violate any applicable laws or regulations</li>
            <li>Infringe on the intellectual property rights of others</li>
            <li>Upload malicious content or attempt to compromise our systems</li>
            <li>Use the Service for any unlawful or harmful purpose</li>
            <li>Misrepresent your identity or affiliation</li>
            <li>Attempt to reverse engineer or extract the AI models</li>
            <li>Use automated systems to access the Service without permission</li>
          </ul>
        </section>

        <section className="mt-8">
          <h2>5. Intellectual Property</h2>
          
          <h3>5.1 Our Intellectual Property</h3>
          <p>
            The Service, including its original content, features, and functionality, is 
            owned by Lighted and is protected by South African and international intellectual 
            property laws.
          </p>

          <h3>5.2 Your Content</h3>
          <p>
            You retain ownership of the voice notes you submit and the exegesis briefs 
            generated from them. By using our Service, you grant us a limited license to 
            process your content solely to provide the Service to you.
          </p>

          <h3>5.3 AI-Generated Content</h3>
          <p>
            Exegesis briefs generated by our AI are provided for your personal use in sermon 
            preparation. You may use, modify, and incorporate this content into your sermons. 
            We make no claim to the final works you create using our Service.
          </p>
        </section>

        <section className="mt-8">
          <h2>6. Disclaimer of Warranties</h2>
          <p>
            THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY 
            KIND, EITHER EXPRESS OR IMPLIED.
          </p>
          <p>We specifically disclaim:</p>
          <ul>
            <li>Any warranty that the Service will be uninterrupted, secure, or error-free</li>
            <li>Any warranty regarding the accuracy, reliability, or completeness of AI-generated content</li>
            <li>Any warranty regarding the theological correctness of exegesis briefs</li>
          </ul>
          <p>
            <strong>Important:</strong> AI-generated exegesis briefs are tools to assist your 
            sermon preparation. They are not substitutes for your own theological training, 
            biblical scholarship, or pastoral discernment. You are responsible for reviewing 
            and verifying all content before use.
          </p>
        </section>

        <section className="mt-8">
          <h2>7. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by South African law, including Section 61 of the 
            Consumer Protection Act:
          </p>
          <ul>
            <li>
              We shall not be liable for any indirect, incidental, special, consequential, 
              or punitive damages arising from your use of the Service
            </li>
            <li>
              Our total liability shall not exceed the amount you paid us (if any) in the 
              12 months preceding the claim
            </li>
          </ul>
          <p>
            Nothing in these Terms excludes or limits liability for fraud, gross negligence, 
            or any other liability that cannot be excluded by law.
          </p>
        </section>

        <section className="mt-8">
          <h2>8. Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless Lighted, its officers, directors, 
            employees, and agents from any claims, damages, losses, or expenses (including 
            legal fees) arising from:
          </p>
          <ul>
            <li>Your use of the Service</li>
            <li>Your violation of these Terms</li>
            <li>Your violation of any rights of a third party</li>
            <li>Your use of AI-generated content in sermons or other works</li>
          </ul>
        </section>

        <section className="mt-8">
          <h2>9. Third-Party Services</h2>
          <p>
            Our Service integrates with third-party services including Google, Telegram, and 
            various AI providers. Your use of these services is subject to their respective 
            terms of service and privacy policies.
          </p>
        </section>

        <section className="mt-8">
          <h2>10. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your account and access to the 
            Service at our sole discretion, without notice, for conduct that we believe:
          </p>
          <ul>
            <li>Violates these Terms</li>
            <li>Is harmful to other users or our Service</li>
            <li>Is harmful to our legitimate business interests</li>
          </ul>
          <p>
            You may terminate your account at any time by contacting us. Upon termination, 
            your right to use the Service will immediately cease.
          </p>
        </section>

        <section className="mt-8">
          <h2>11. Cooling-Off Period (CPA Compliance)</h2>
          <p>
            In accordance with Section 16 of the Consumer Protection Act, if you are a 
            consumer as defined in the CPA and have entered into this agreement as a result 
            of direct marketing, you have the right to cancel this agreement without reason 
            or penalty within 5 business days of the date you first accessed the Service.
          </p>
        </section>

        <section className="mt-8">
          <h2>12. Dispute Resolution</h2>
          <p>
            Any dispute arising from these Terms or your use of the Service shall be:
          </p>
          <ol>
            <li>First, addressed through good-faith negotiation between the parties</li>
            <li>If unresolved, submitted to mediation in accordance with South African law</li>
            <li>If mediation fails, resolved through arbitration or the courts of South Africa</li>
          </ol>
          <p>
            Nothing in this clause prevents either party from seeking urgent interim relief 
            from a court of competent jurisdiction.
          </p>
        </section>

        <section className="mt-8">
          <h2>13. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of 
            the Republic of South Africa, without regard to its conflict of law provisions.
          </p>
        </section>

        <section className="mt-8">
          <h2>14. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. We will provide notice 
            of material changes by posting the updated Terms on our website and updating the 
            "Last Updated" date. Your continued use of the Service after such changes 
            constitutes your acceptance of the new Terms.
          </p>
        </section>

        <section className="mt-8">
          <h2>15. Severability</h2>
          <p>
            If any provision of these Terms is found to be unenforceable or invalid, that 
            provision shall be limited or eliminated to the minimum extent necessary, and the 
            remaining provisions shall remain in full force and effect.
          </p>
        </section>

        <section className="mt-8">
          <h2>16. Contact Information</h2>
          <p>For any questions about these Terms, please contact us:</p>
          <ul>
            <li><strong>Email:</strong> legal@lighted.life</li>
            <li><strong>Website:</strong> https://lighted.life</li>
          </ul>
        </section>

        <div className="mt-12 pt-8 border-t">
          <Link href="/" className="text-primary hover:underline">
            ← Back to Home
          </Link>
        </div>
      </div>
    </main>
  );
}
